export const EVENT_TYPES = Object.freeze({
  CREATED: 'CREATED',
  USAGE_LOGGED: 'USAGE_LOGGED',
  CONFIRMED: 'CONFIRMED',
  DECLINED_REVERTED: 'DECLINED_REVERTED',
  ADMIN_CORRECTED: 'ADMIN_CORRECTED',
});
