export const NOTIFICATION_TYPES = Object.freeze({
  ENTRY_DECLINED: 'ENTRY_DECLINED',
  MESSAGE: 'MESSAGE',
  CORRECTION_REQUESTED: 'CORRECTION_REQUESTED',
  CORRECTION_RESOLVED: 'CORRECTION_RESOLVED',
  CORRECTION_REJECTED: 'CORRECTION_REJECTED',
});

export const CORRECTION_CATEGORIES = Object.freeze([
  'WRONG_WEIGHT',
  'WRONG_SPECS',
  'WRONG_MASTER_CODE',
  'WRONG_REEL_NO',
  'WRONG_MILL_SUPPLIER',
  'OTHER',
]);

export const CORRECTION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
});
